spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/neletaa?useUnicode=true&characterEncoding=utf8
    username: kjy
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        format_sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'

